version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing packages...
      - export PUPPETEER_DOWNLOAD_HOST=https://npm.taobao.org/mirrors
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng  -v
      #- npm run lint
      #- npm run test:ci
      - npm run build$ENV
      - pwd
      - ls -l
      - cd  ./dist/pdf-pw-remover
      - aws s3 sync ./ s3://$CODE_ARTIFACT_BUCKET --delete
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - deployspec.yml
    - dist/**/*
    - script/exports.sh
