version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing packages...
      - export PUPPETEER_DOWNLOAD_HOST=https://npm.taobao.org/mirrors
      - npm install && npm install -g @angular/cli@13
  build:
    commands:
      - echo Build started on `date`
      - ng version
      #- npm run lint
      #- npm run test:ci
      - npm run build$ENV
           
  post_build:
    commands:
      # - echo Copying files to S3 Bucket
      # - ls -l
      # - cd  ./dist/pdf-pw-remover
      # #copy dist folder to SPA  S3 Bucket
      # - aws s3 sync ./ s3://$CODE_ARTIFACT_BUCKET --delete
      - echo Build completed on `date`
artifacts:
  files:
    - deployspec.yml
    - dist/**/*
